- springql-core/src/stream_engine.rs
- springql-core/src/stream_engine/autonomous_executor/scheduler/flow_efficient_scheduler.rs
- springql-core/src/stream_engine/autonomous_executor/server_instance/source/net.rs
- springql-core/src/stream_engine/autonomous_executor/test_support/factory.rs
- springql-core/tests/e2e_row_level_rs.rs
- test-foreign-service/src/source.rs
- test-foreign-service/src/source/source_input.rs
Also it accepts only 1 connection from now on
> refactor: TestForeignSource takes input as enum

- springql-core/src/stream_engine.rs
- springql-core/src/stream_engine/autonomous_executor.rs
- springql-core/tests/e2e_row_level_rs.rs
- test-foreign-service/Cargo.toml
- test-foreign-service/src/source.rs
- test-foreign-service/src/source/source_input.rs
- test-foreign-service/src/source/source_input/timed_stream.rs
- test-foreign-service/src/source/source_input/timed_stream/file_parser.rs
- test-foreign-service/src/source/source_input/timed_stream/file_type.rs
- test-foreign-service/src/source/source_input/timed_stream/timer.rs
```rust
#[test]
fn test_timed_stream() {
let timed_stream = TimedStream::new(
FileType::Tsv,
"/Users/sho.nakatani/Downloads/VSC1S03-rfc3339.csv",
"Time".to_string(),
DateTime::parse_from_rfc3339("2020-10-21T11:00:15.000+09:00").unwrap(),
)
.unwrap();
let input = TestForeignSourceInput::new_timed_stream(timed_stream);
for j in input {
println!("{}", j.unwrap());
}
}
```
> feat: TimedStream

- springql-core/src/stream_engine/autonomous_executor/performance_metrics.rs
- springql-core/src/stream_engine/autonomous_executor/queue/row_queue_repository.rs
- springql-core/src/stream_engine/autonomous_executor/queue/window_queue_repository.rs
- springql-core/src/stream_engine/autonomous_executor/task/sink_task/sink_writer/sink_writer_repository.rs
- springql-core/src/stream_engine/autonomous_executor/task/source_task/source_reader/source_reader_repository.rs
> fix: use parking_lot::RwLock instead of std::sync::RwLock

- .github/workflows/ci.yml
> ci: upload to codecov

- Makefile.toml
thx to @kazuk
https://twitter.com/kazuk/status/1499540373600755712?s=20&t=tGxKDUnkD0n5Fzpt_d_fww
> build: add `help` step for cargo make

- .github/workflows/ci.yml
- springql-core/examples/demo_pipeline.rs
> fix: example fails by connection refused error

- CHANGELOG.md
- springql-core/src/api/low_level_rs/spring_config.rs
Fixes: #71 
see:
- https://github.com/SpringQL/SpringQL/issues/71#issuecomment-1089856816
- https://github.com/SpringQL/SpringQL/issues/71#issuecomment-1089946201
> fix: out-of-order processing

- .github/workflows/ci.yml
> ci: use macos-latest for test and example jobs

- springql-core/Cargo.toml
> build: disable unused default-features

- Makefile.toml
- springql-core/src/stream_engine/autonomous_executor/task/sink_task/sink_writer/net.rs
> ci: change log level in test job

- springql-core/src/stream_engine.rs
- springql-core/src/stream_engine/autonomous_executor.rs
- springql-core/src/stream_engine/autonomous_executor/memory_state_machine_worker.rs
- springql-core/src/stream_engine/autonomous_executor/memory_state_machine_worker/memory_state_machine_worker_thread.rs
- springql-core/src/stream_engine/autonomous_executor/performance_monitor_worker.rs
- springql-core/src/stream_engine/autonomous_executor/performance_monitor_worker/performance_monitor_worker_thread.rs
- springql-core/src/stream_engine/autonomous_executor/purger_worker.rs
- springql-core/src/stream_engine/autonomous_executor/purger_worker/purger_worker_thread.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/generic_worker_pool.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/generic_worker_pool/generic_worker.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/generic_worker_pool/generic_worker/generic_worker_thread.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/source_worker_pool.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/source_worker_pool/source_worker.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/source_worker_pool/source_worker/source_worker_thread.rs
- springql-core/src/stream_engine/autonomous_executor/worker/worker_handle.rs
- springql-core/src/stream_engine/autonomous_executor/worker/worker_thread.rs
> fix(internal): Waits for all workers to get ready in setup sequence

- Makefile.toml
- coverage_grcov.makefile.toml
Close #110 
add SKIP_INSTALL_GRCOV environment variable.
> skip to install grcov

- .cargo/config.toml
- Makefile.toml
> feat: add doc alias for project configuration

- springql-core/src/pipeline/relation/sql_type.rs
- test-web-console-mock/src/lib.rs
> Small typos

- CHANGELOG.md
- springql-core/src/expression.rs
- springql-core/src/lib.rs
- springql-core/src/stream_engine/autonomous_executor/row/foreign_row/sink_row.rs
- springql-core/src/stream_engine/autonomous_executor/task/window/panes.rs
- springql-core/src/stream_engine/autonomous_executor/task/window/watermark.rs
- springql-core/src/stream_engine/time/duration.rs
- springql-core/src/stream_engine/time/timestamp.rs
- springql-core/src/stream_engine/time/timestamp/system_timestamp.rs
- springql-core/src/time.rs
Fixes: #171
- introduce new-type wrapper for chrono types
> Wrap chrono types

- CHANGELOG.md
- deny.toml
> turn off RUSTSEC-2020-0071

- CHANGELOG.md
- Makefile.toml
- deadlinks.expected
Fixes: #166
add "ignore known deadlink"
- add `deadlink.expected` file
- sort/uniq diff to `cargo-deadlinks` result
> ci: add ignore to known deadlink

- Makefile.toml
Fixes: #196
- add throttle option for mlc
> ci: add throttle 15

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- springql-core/Cargo.toml
> build: bump up MSRV to 1.56.1

- CHANGELOG.md
- springql/Cargo.toml
> fix: reqwest to HTTPS

- CHANGELOG.md
- springql-core/src/api.rs
- springql-core/src/api/error/foreign_info.rs
- springql-core/src/connection.rs
- springql-core/src/pipeline/source_reader_model/source_reader_type.rs
- springql-core/src/sql_processor/sql_parser/pest_parser_impl.rs
- springql-core/src/stream_engine.rs
- springql-core/src/stream_engine/autonomous_executor/row.rs
- springql-core/src/stream_engine/autonomous_executor/row/column/stream_column.rs
- springql-core/src/stream_engine/autonomous_executor/row/foreign_row/source_row.rs
- springql-core/src/stream_engine/autonomous_executor/task/source_task/source_reader.rs
- springql-core/src/stream_engine/autonomous_executor/task/source_task/source_reader/in_memory_queue.rs
- springql-core/src/stream_engine/autonomous_executor/task/source_task/source_reader/source_reader_factory.rs
- springql/tests/e2e_connect_2_pipelines.rs
Fixes part of : #206 
In that this PR does not provide any way to create a SpringRow from apps.
- Add `IN_MEMORY_QUEUE` source reader
- Add `SpringPipeline::push()` public API
> feat: in-memory queue source reader

- CHANGELOG.md
- Makefile.toml
- springql/examples/doc_app1.rs
- springql/examples/doc_app2.rs
Fixes: #140
- start netcat on pipeline setup completed.
> ci: fix fleaky example-run

- springql-core/src/pipeline/name.rs
- springql-core/src/stream_engine/autonomous_executor/row/stream_row.rs
> refactor: rm unused `arrival_rowtime`

- CHANGELOG.md
- springql-core/src/api.rs
- springql-core/src/api/spring_source_row.rs
- springql/tests/feat_source_row.rs
Fixes: #206 
Add `SpringSourceRow` and its constructor `SpringSourceRow::from_json()`
> feat: SpringSourceRow::from_json()

- CHANGELOG.md
- springql-core/src/api.rs
- springql-core/src/api/spring_source_row.rs
- springql-core/src/api/spring_source_row/spring_source_row_builder.rs
- springql-core/src/stream_engine/autonomous_executor/row/schemaless_row.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible/blob.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible/boolean.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible/event_duration.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible/float.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible/int.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible/text.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_convertible/timestamp.rs
- springql-core/src/stream_engine/autonomous_executor/row/value/sql_value/nn_sql_value.rs
- springql/Cargo.toml
- springql/tests/feat_source_row.rs
- Add `SpringSourceRowBuilder` to enable source rows' construction with binary data.
- not necessary because the doc does not include Rust / C client API details
> feat: SpringSourceRowBuilder

- CHANGELOG.md
- springql-core/src/stream_engine/autonomous_executor/task.rs
- springql-core/src/stream_engine/autonomous_executor/task/processed_rows.rs
- springql-core/src/stream_engine/autonomous_executor/task/pump_task.rs
- springql-core/src/stream_engine/autonomous_executor/task/pump_task/pump_subtask/query_subtask.rs
- springql-core/src/stream_engine/autonomous_executor/task/sink_task.rs
- springql-core/src/stream_engine/autonomous_executor/task/source_task.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/task_worker_thread_handler.rs
- springql/examples/cpu_usage.rs
- springql/examples/in_memory.rs
Fixes: #227 
- add ProcessedRow
- add sleep when `ProcessedRow::is_empty()`
> fix: high CPU usage even when no rows are coming from source

- CHANGELOG.md
- springql-core/src/stream_engine/autonomous_executor/worker/worker_thread.rs
- springql/examples/in_memory.rs
Fixes: #231 
- add sleep when state is not integral
> fix: High CPU usage at launch

- .github/workflows/release.yml
remove tagging "springql@VERSION" and "springql-core@VERSION".
> ci: remove verbose tag

- deny.toml
https://github.com/dtolnay/unicode-ident/pull/9 changed the license.
<https://spdx.org/licenses/Unicode-DFS-2016.html> seems to say we are not restricted from anything if we preserve the copyright and permission notice.
> ci: allow Unicode-DFS-2016

- .github/workflows/release.yml
- springql-core/src/expression/boolean_expression.rs
- springql-core/src/expression/boolean_expression/comparison_function.rs
- springql-core/src/expression/boolean_expression/logical_function.rs
- springql-core/src/expression/boolean_expression/numerical_function.rs
- springql-core/src/expression/function_call.rs
- springql-core/src/pipeline/pump_model/window_operation_parameter.rs
- springql-core/src/pipeline/pump_model/window_operation_parameter/aggregate.rs
- springql-core/src/pipeline/pump_model/window_operation_parameter/join_parameter.rs
- springql-core/src/sql_processor/sql_parser/syntax.rs
- springql-core/src/stream_engine/autonomous_executor/performance_monitor_worker/web_console_reporter/web_console_request.rs
- springql-core/src/stream_engine/command/query_plan/query_plan_operation.rs
- springql/tests/test_support/request_body.rs
CI clippy lint failing.
fix lint error
> refactor: fix clippy lint

- .github/workflows/ci.yml
- CHANGELOG.md
- springql-core/Cargo.toml
> Bump Minnimum Supported Rust Version to 1.63

- springql-core/src/pipeline/option/net_client_options.rs
- springql-core/src/pipeline/option/net_server_options.rs
- springql-core/src/sql_processor/sql_parser/pest_parser_impl.rs
- springql-core/src/stream_engine/autonomous_executor/performance_metrics/metrics_update_command/metrics_update_by_task_execution.rs
- springql-core/src/stream_engine/autonomous_executor/performance_monitor_worker/performance_monitor_worker_thread.rs
- springql-core/src/stream_engine/autonomous_executor/row/column_values.rs
- springql-core/src/stream_engine/autonomous_executor/task/sink_task/sink_writer.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/generic_worker_pool.rs
- springql-core/src/stream_engine/autonomous_executor/task_executor/source_worker_pool.rs
- springql/tests/e2e_high_level_rs.rs
clippy warnings
Fix lint warnings
> refactor: Fix clippy warnings
